- name: Hello World Sample with variables
  hosts: all
  vars: 
    guestName: "World"
    greeting: "Hello"
  tasks:
    - name: Hello Message
      debug:
        msg: "{{ greeting }}, {{ guestName }}!"
